# Generated by Django 5.1.1 on 2024-09-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('conn_type', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL'), ('redis', 'Redis')], max_length=50)),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField()),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
