# Generated by Django 5.1.1 on 2024-10-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conn_name', models.CharField(max_length=255)),
                ('conn_type', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=255)),
                ('pwd', models.CharField(max_length=255)),
                ('extra', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
