# Generated by Django 5.1.1 on 2024-10-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='conn_type',
            field=models.CharField(choices=[('oracle', 'Oracle'), ('postgresql', 'Postgresql')], max_length=255),
        ),
    ]
