# Generated by Django 5.0.3 on 2024-10-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_alter_connection_conn_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='conn_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
