# Generated by Django 5.1.1 on 2024-10-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_alter_connection_conn_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='srcTableBas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('table_name', models.CharField(max_length=255)),
                ('conn_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.connection')),
            ],
        ),
        migrations.CreateModel(
            name='srcTableDtl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=255)),
                ('column_comment', models.CharField(max_length=255)),
                ('column_type', models.CharField(max_length=255)),
                ('column_column_rk', models.IntegerField()),
                ('if_yn', models.BooleanField(default=True)),
                ('table_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connection.srctablebas')),
            ],
            options={
                'indexes': [models.Index(fields=['table_id', 'if_yn'], name='connection__table_i_fba8e8_idx')],
            },
        ),
    ]
